name: interstate
description: a library for distributed systems in dart 
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  json: ^0.20.4
  macros: ^0.1.3-main.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0



